### ISSUE TITLE
ISSU002 Remove 'Number of People'

### ISSUE THREAD

**Issue by nherriot** [SamsungResearchUK-IoT-Meetup/kivy-calendar#3]
The 'required people' field needs to change to an email list. The list should be checked and formatted.
- [x] Items are checked that they are formatted as an email 'myemail@email.com
- [x] Items can be separated by ';' 
- [x] Items are placed in a list within the new meeting dictionary

**Comment by nherriot** [comment]
Created branch:

ISSU002-Remove-Number-of-People.

Tested and committed in commit ID: 
https://github.com/SamsungResearchUK-IoT-Meetup/kivy-calendar/commit/a352662b79d983ab0a8817e4f7c2b992dfb03d70

**Comment by nherriot** [comment]
Merged branch into 'master'.
Files changed were: schedulemeeting.kv and schedulemeeting.py

**Comment by JMMarchant** [comment]
Looks good!
