### ISSUE TITLE
ISSU004 Make "Schedule Deadline", "Earliest" and "Latest" a DateTime objects

### ISSUE THREAD

**Issue by nherriot** [SamsungResearchUK-IoT-Meetup/kivy-calendar#5]
The 'Schedule Deadline' is currently set at how many days in the future the deadline will be. This should be a date time object. It should not be able to be set at a date earlier than the requested date of the latest meeting.
- [x] Schedule deadline is a date time object.
- [x] The deadline should not be allowed to be set at a time earlier than the requested date of the latest meeting.

**Comment by JMMarchant** [comment]
Other fields additionally need this
